### ISSUE TITLE
Get build APK

### ISSUE THREAD

**Issue by rakshans2** [beevelop/docker-ionic#124]
How to get build apk from inside the container to host machine

//My docker file
```
FROM beevelop/ionic

WORKDIR /app

ADD ./ /app

RUN npm install && ionic cordova build android --prod
```

Apk is build inside container.. how to get it to host machine

**Comment by eduardor2k** [comment]
### Build Android

docker run -v /path/to/ionic/project:/root/ionic -it beevelop/ionic bash

```Run your application
$ cd /root/ionic
$ npm install
$ ionic cordova build --release android
```

**Comment by beevelop** [comment]
@rakshans2 @eduardor2k Thank you for the input. I'll add the instructions to obtain the APK files to the README.
