### ISSUE TITLE
No ssh installed - can't use ionic pro

### ISSUE THREAD

**Issue by joshbmarshall** [beevelop/docker-ionic#130]
I know I can use this as a base image and add ssh myself but thought perhaps others would benefit from having ssh installed so that ionic pro can be used.

**Comment by beevelop** [comment]
Thank you for the input. I think it's a good idea to include those basic dependencies.

**Comment by beevelop** [comment]
Should be available in the next few minutes (after Docker Hub triggered and finished the new image build).
