### ISSUE TITLE
Before building your project, you need to accept the license agreements and complete the installation of the missing components

### ISSUE THREAD

**Issue by RsknCankov** [beevelop/docker-ionic#142]
Hello I am using the image as base for building release .apk for android , after running ionic Cordova build android --release , following error message is displayed: 
You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.

I tried with ./sdkmanager --licenses ,but without any success

**Comment by Tgure** [comment]
@RsknCankov I was able to get around this adding the following two commands before by build command.
- yes | $ANDROID_HOME/tools/bin/sdkmanager --update
- yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true

**Comment by raujonas** [comment]
@Tgure I got the same error since a few days, the two lines above do not help me to get the build passing. The script shows the license agreement, but it seems that accepting them is not working:

```
---------------------------------------
Accept? (y/N): done
ERROR: Job failed: exit code 1
```

**Comment by Tgure** [comment]
@raujonas The above is still working for me, it shows the following at the end of all the agreements for me.  Not sure why yours would not work.

---------------------------------------
Accept? (y/N): All SDK package licenses accepted

**Comment by raujonas** [comment]
Hi @Tgure, thank you very much for your answer. It's now working since I added "echo" in front of both statements, but I am currently not sure why this makes the difference.

```
- echo yes | $ANDROID_HOME/tools/bin/sdkmanager --update
- echo yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
```

Moreover it does not print "Accept? (y/N): All SDK package licenses accepted" like you stated, in my case it says that I did not accept 4 licenses, it only accepts the "Android Software Development Kit License Agreement". Do you know how I can achieve to accept also the other licenses?

**Comment by Tgure** [comment]
@raujonas I am running this in a bitbucket pipeline, not sure how that differs from what you are doing.  My pipeline command order is as follows:

- apt-get update
- npm install
- yes | $ANDROID_HOME/tools/bin/sdkmanager --update
- yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
- ionic cordova build android

**Comment by Trexology** [comment]
sorry, a docker noob here. How/where do I run the 2 commands to accept the license agreement?

I build the image following the original instructions
`docker build -t beevelop/ionic github.com/beevelop/docker-ionic`

I'm using the image for my local development environment.

**Comment by raujonas** [comment]
I used this image in my gitlab ci. So I ran the 2 images in my android build stage after the npm install and before the ionic build.

I am not sure about a local docker image, but I would suggest that you have to run them inside the docker container where you started the image before.
