### ISSUE TITLE
Great repo!

### ISSUE THREAD

**Issue by pedrofurtado** [beevelop/docker-ionic#161]
Thanks for this great repo! I am new into ionic, and setup the whole environment is a pain. This repo make it so easy. And the best part is that you actively maintain the version of dependencies (android, java, node, cordova, and so on) updated.
Thanks, @beevelop ! :+1:

**Comment by beevelop** [comment]
@pedrofurtado thank you for the motivating words. I'll give my best to keep this Docker images up-to-date. Improvements, PRs, etc. are always appreciated – as you already did 🍻
