### ISSUE TITLE
Container update

### ISSUE THREAD

**Issue by divanvb** [beevelop/docker-ionic#203]
Hey man

When will the container be updated again?

**Comment by beevelop** [comment]
Now ;) You can check it out in a few minutes (when Docker Hub finishes building).

**Comment by divanvb** [comment]
Thank you! Just a quick question, this will work with Ionic 4 & Capacitor, right? The process still stays relatively the same.

**Comment by beevelop** [comment]
Never tried Capacitor before. But you can give it a shot.
