### ISSUE TITLE
Update nodejs version to support Angular CLI 8.0+

### ISSUE THREAD

**Issue by robingenz** [beevelop/docker-ionic#213]
Hi,
when trying to build my app (ionic@4.7.1, angular@8.1.3) with your docker, the following error message appears:
```
You are running version v8.15.0 of Node.js, which is not supported by Angular CLI 8.0+.
The official Node.js version that is supported is 10.9 or greater.
```
It would be nice to update the nodejs version.

**Comment by Drezounet** [comment]
How did you solve your problem ? :)

**Comment by robingenz** [comment]
I've created my own Docker image with the required package versions.
