### ISSUE TITLE
Android SDK license agreement needs acceptance

### ISSUE THREAD

**Issue by haneyman** [beevelop/docker-ionic#226]
during the "ionic cordova build android" the build switches to SDK 28 and then gets the message "To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager. Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /opt/android
"

I believe it needs to do something similar to:
yes | sdkmanager --licenses && sdkmanager --update

**Comment by Drezounet** [comment]
in my docker file, i put this : 
`
RUN echo y | android update sdk --no-ui --all --filter "android-27"
RUN echo y | android update sdk --no-ui --all --filter "android-28"
RUN echo y | $ANDROID_HOME/tools/bin/sdkmanager --update



RUN yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
`
