### ISSUE TITLE
ionic@6.4.3

### ISSUE THREAD

**Issue by jeremyTyriaux** [beevelop/docker-ionic#246]
Hi and thanks for your work. I use your docker image for a long time, but now i need to update my projects to the last version of ionic.

Could you please upgrade the docker file ?

Thanks

**Comment by beevelop** [comment]
Oh yeah, we need to switch to `@ionic/cli`. Sorry, it's been quite a long time since this Docker image was born. I'll start working on a big update in the next few days. I assume, the old checks (via Travis) won't work either.

**Comment by arek159** [comment]
as a temporary workaround, i've created my docker image
https://hub.docker.com/r/arek159/ionic-builder

sample usage for ionic application, using gitlab ci:

`stages:
  - package

package-android:
  image: arek159/ionic-builder
  stage: package
  script:
    - ionic cordova build android --prod --release
    - cp platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk app-release-unsigned.apk
    - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore mskigroup.keystore app-release-unsigned.apk -storepass $JARSIGNER -keypass $JARSIGNER mskigroup
    - zipalign -v 4 app-release-unsigned.apk application.apk
  artifacts:
    paths:
      - application.apk

`
