### ISSUE TITLE
Cannot access http://localhost:8100 from host 

### ISSUE THREAD

**Issue by GSWKW** [beevelop/docker-ionic#250]
Hello all,
after I did the following steps, I am not able to access the webpage served from ionic:
1) pulled the image
2) started the container (with exposing port 8100)
3) created an own simple app with: ionic start myApp tabs
4) moved into the myApp directory and started it with: ionic serve (--external)

--> my browser still does not show the page.

Do you have any advice or hint for me?

**Comment by GSWKW** [comment]
I solved the problem by using 

`ionic serve --address=0.0.0.0`

But I have not found any good explanation why it works this way.
Do you have any information for this workaround?

**Comment by beevelop** [comment]
Looks like the default command only listens on localhost. If you run it in a container, the `localhost` of your container is **not** the localhost of your host machine. This can be applied to all kind of services which run in containers. Most often you need to expose them on all interfaces (what you did with the `address` command).

AFAICT it should also work using the `--external` command line flag: https://ionicframework.com/docs/cli/commands/serve#option-external

**Comment by aniskoubaa** [comment]
Hi
I am having the same issue.  I tried even with 
ionic serve --address=0.0.0.0
ionic serve --external 

and still cannot access http://localhost:8100

Is there any solution?

**Comment by beevelop** [comment]
Could you provide the exact `docker` command you used for launching the container?
