### ISSUE TITLE
Update for Ionic 3?

### ISSUE THREAD

**Issue by c0bra** [beevelop/docker-ionic#80]
@beevelop any chance you could do a release for the latest version of Ionic?

Or if there's another option you could point to for ionic dev environments that'd be great.

**Comment by beevelop** [comment]
@c0bra on it. Unfortunately my IFTTT automation for the latest releases stopped working. The `next` will be merged to `master` ASAP.

**Comment by beevelop** [comment]
@c0bra `v3.7.0` has just been released.

**Comment by c0bra** [comment]
@beevelop great, thanks!
